/**
 * internshipsData.js
 * 
 * Curated list of fresher/tech internship & new-grad roles.
 * To update: add/remove objects from the array below.
 * Fields: id, employer_name, employer_logo (optional), job_title, job_city,
 *         job_employment_type, job_apply_link, job_posted_at, salary,
 *         tags (skills), description, is_fresher, is_remote, is_hot
 */

export const INTERNSHIPS = [
    // ─── FAANG / Big Tech ──────────────────────────────────────────────────────
    {
        id: 1,
        employer_name: "Google",
        employer_logo: "https://logo.clearbit.com/google.com",
        job_title: "Software Engineering Intern",
        job_city: "Hyderabad",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.google.com/jobs/results/?jex=ENTRY_LEVEL",
        job_posted_at: "2025-04-20",
        salary: "₹1,50,000/mo",
        tags: ["C++", "Python", "DSA", "Distributed Systems"],
        description:
            "Work on large-scale systems powering billions of users. Interns contribute to real products across Search, Maps, YouTube, and Cloud. Strong DSA fundamentals required.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 2,
        employer_name: "Microsoft",
        employer_logo: "https://logo.clearbit.com/microsoft.com",
        job_title: "Software Engineer Intern (SDE)",
        job_city: "Hyderabad",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.microsoft.com/students/us/en/india-internship",
        job_posted_at: "2025-04-18",
        salary: "₹1,20,000/mo",
        tags: ["Java", "C#", "Azure", "System Design"],
        description:
            "Contribute to Microsoft's cloud and productivity products. Interns work alongside full-time engineers on Azure, Microsoft 365, and Teams. Pre-final and final year students.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 3,
        employer_name: "Amazon",
        employer_logo: "https://logo.clearbit.com/amazon.com",
        job_title: "SDE Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://amazon.jobs/en/teams/internships-for-students",
        job_posted_at: "2025-04-15",
        salary: "₹1,00,000/mo",
        tags: ["Java", "AWS", "OOP", "DSA"],
        description:
            "Design and build features for Amazon's e-commerce, logistics, or AWS platform. Interns own a project end-to-end. Leadership Principles assessment included in interviews.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 4,
        employer_name: "Meta",
        employer_logo: "https://logo.clearbit.com/meta.com",
        job_title: "Software Engineer Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://metacareers.com/jobs",
        job_posted_at: "2025-04-10",
        salary: "₹1,80,000/mo",
        tags: ["Python", "React", "GraphQL", "Distributed Systems"],
        description:
            "Build the next generation of social connectivity at scale. Work on Instagram, WhatsApp, or VR infrastructure. Strong systems and coding skills expected.",
        is_fresher: true,
        is_remote: true,
        is_hot: true,
    },
    {
        id: 5,
        employer_name: "Apple",
        employer_logo: "https://logo.clearbit.com/apple.com",
        job_title: "Software Engineer Intern (iOS/macOS)",
        job_city: "Hyderabad",
        job_employment_type: "Internship",
        job_apply_link: "https://jobs.apple.com/en-in/search?team=internships-STDNT-INTRN",
        job_posted_at: "2025-04-08",
        salary: "₹1,40,000/mo",
        tags: ["Swift", "Objective-C", "Xcode", "CoreML"],
        description:
            "Develop features for iOS, macOS, or developer tools. Apple interns ship real code to millions of devices. Passion for Apple's design philosophy is a plus.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── Indian Unicorns ────────────────────────────────────────────────────────
    {
        id: 6,
        employer_name: "Flipkart",
        employer_logo: "https://logo.clearbit.com/flipkart.com",
        job_title: "SDE Intern (Backend)",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://www.flipkartcareers.com/#!/joblist",
        job_posted_at: "2025-04-22",
        salary: "₹80,000/mo",
        tags: ["Java", "Kafka", "MySQL", "Spring Boot"],
        description:
            "Work on Flipkart's high-traffic backend services handling millions of orders daily. Interns work on search, supply chain, or payments. High-performance engineering culture.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 7,
        employer_name: "Zepto",
        employer_logo: "https://logo.clearbit.com/zepto.co.in",
        job_title: "Software Engineer Intern",
        job_city: "Mumbai",
        job_employment_type: "Internship",
        job_apply_link: "https://www.zepto.co.in/jobs",
        job_posted_at: "2025-04-21",
        salary: "₹75,000/mo",
        tags: ["Go", "React", "PostgreSQL", "Redis"],
        description:
            "Join one of India's fastest-growing quick-commerce startups. Work on logistics optimization, real-time tracking, or consumer app features. Fast-paced, high ownership.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 8,
        employer_name: "Swiggy",
        employer_logo: "https://logo.clearbit.com/swiggy.com",
        job_title: "Product & Engineering Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.swiggy.com",
        job_posted_at: "2025-04-19",
        salary: "₹70,000/mo",
        tags: ["Python", "Node.js", "MongoDB", "Microservices"],
        description:
            "Build systems that power food delivery for 500+ cities. Work on consumer app, restaurant platform, or Swiggy Instamart. Strong focus on metrics and data-driven development.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 9,
        employer_name: "Razorpay",
        employer_logo: "https://logo.clearbit.com/razorpay.com",
        job_title: "Frontend Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://razorpay.com/jobs",
        job_posted_at: "2025-04-17",
        salary: "₹65,000/mo",
        tags: ["React", "TypeScript", "GraphQL", "Figma"],
        description:
            "Build the payment interfaces used by 8M+ businesses in India. Work on Razorpay Dashboard, Payment Links, or the new RazorpayX banking product. Pixel-perfect UI focus.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 10,
        employer_name: "CRED",
        employer_logo: "https://logo.clearbit.com/cred.club",
        job_title: "Android / iOS Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.cred.club",
        job_posted_at: "2025-04-14",
        salary: "₹60,000/mo",
        tags: ["Kotlin", "Swift", "Jetpack Compose", "Clean Architecture"],
        description:
            "Craft premium mobile experiences for India's most design-conscious fintech. CRED is known for pushing UI/UX boundaries. Strong portfolio of personal apps is a big plus.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 11,
        employer_name: "Meesho",
        employer_logo: "https://logo.clearbit.com/meesho.com",
        job_title: "Data Engineering Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://meesho.io/jobs",
        job_posted_at: "2025-04-12",
        salary: "₹55,000/mo",
        tags: ["Python", "Spark", "Airflow", "BigQuery"],
        description:
            "Build data pipelines powering Meesho's social commerce platform serving Tier 2/3 India. Work on seller analytics, recommendation systems, and growth dashboards.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 12,
        employer_name: "PhonePe",
        employer_logo: "https://logo.clearbit.com/phonepe.com",
        job_title: "Backend SDE Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.phonepe.com",
        job_posted_at: "2025-04-11",
        salary: "₹70,000/mo",
        tags: ["Java", "Spring Boot", "Kafka", "MySQL"],
        description:
            "Work on UPI transaction systems processing 14B+ transactions/year. Intern on payments core, fraud detection, or merchant platform. High reliability engineering focus.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },

    // ─── FinTech & Banking Tech ─────────────────────────────────────────────────
    {
        id: 13,
        employer_name: "Groww",
        employer_logo: "https://logo.clearbit.com/groww.in",
        job_title: "Full Stack Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://groww.in/p/careers",
        job_posted_at: "2025-04-20",
        salary: "₹60,000/mo",
        tags: ["React", "Node.js", "PostgreSQL", "Redis"],
        description:
            "Build investing experiences for 50M+ users. Work on mutual funds, stocks, or F&O platform. Strong emphasis on performance and accessibility for mobile-first users.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 14,
        employer_name: "Paytm",
        employer_logo: "https://logo.clearbit.com/paytm.com",
        job_title: "Software Developer Intern",
        job_city: "Noida",
        job_employment_type: "Internship",
        job_apply_link: "https://paytm.com/careers",
        job_posted_at: "2025-04-09",
        salary: "₹50,000/mo",
        tags: ["Java", "PHP", "MySQL", "Redis"],
        description:
            "Contribute to Paytm's payments, lending, or insurance products. Exposure to large-scale systems. Good for candidates looking to break into fintech.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 15,
        employer_name: "Jupiter Money",
        employer_logo: "https://logo.clearbit.com/jupiter.money",
        job_title: "iOS Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://jupiter.money/careers",
        job_posted_at: "2025-04-07",
        salary: "₹55,000/mo",
        tags: ["Swift", "UIKit", "SwiftUI", "Combine"],
        description:
            "Build next-gen banking experiences on iOS. Jupiter is a neo-bank challenging traditional banking with a design-first approach. Ideal for iOS developers with a UX eye.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── Global Product Companies (India Offices) ──────────────────────────────
    {
        id: 16,
        employer_name: "Atlassian",
        employer_logo: "https://logo.clearbit.com/atlassian.com",
        job_title: "Software Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://www.atlassian.com/company/careers/interns",
        job_posted_at: "2025-04-16",
        salary: "₹1,10,000/mo",
        tags: ["Java", "Python", "React", "Jira APIs"],
        description:
            "Work on Jira, Confluence, or Trello — tools used by 10M+ teams globally. Atlassian interns have full ownership of features and participate in team demos.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 17,
        employer_name: "Adobe",
        employer_logo: "https://logo.clearbit.com/adobe.com",
        job_title: "Software Engineer Intern (Creative Cloud)",
        job_city: "Noida",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.adobe.com/us/en/india",
        job_posted_at: "2025-04-13",
        salary: "₹90,000/mo",
        tags: ["C++", "JavaScript", "Computer Vision", "ML"],
        description:
            "Work on Photoshop, Premiere Pro, or Firefly AI features. Adobe Noida is a core engineering hub — interns contribute to shipped features in Creative Cloud products.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 18,
        employer_name: "Salesforce",
        employer_logo: "https://logo.clearbit.com/salesforce.com",
        job_title: "Futureforce Tech Intern",
        job_city: "Hyderabad",
        job_employment_type: "Internship",
        job_apply_link: "https://salesforce.com/futureforce",
        job_posted_at: "2025-04-05",
        salary: "₹85,000/mo",
        tags: ["Apex", "JavaScript", "LWC", "Salesforce Platform"],
        description:
            "Salesforce's flagship intern program. Work on CRM, Slack, or MuleSoft. Includes mentorship, networking events, and a potential return offer.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 19,
        employer_name: "Uber",
        employer_logo: "https://logo.clearbit.com/uber.com",
        job_title: "Software Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://www.uber.com/us/en/careers/teams/university/",
        job_posted_at: "2025-04-10",
        salary: "₹1,20,000/mo",
        tags: ["Go", "Python", "Kafka", "Microservices"],
        description:
            "Work on Uber's ride-hailing, Eats, or Freight platform. Bengaluru is a core engineering hub for driver experience and mapping. High ownership from day one.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 20,
        employer_name: "Intuit",
        employer_logo: "https://logo.clearbit.com/intuit.com",
        job_title: "Software Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://careers.intuit.com/students",
        job_posted_at: "2025-04-06",
        salary: "₹95,000/mo",
        tags: ["Java", "React", "Machine Learning", "AWS"],
        description:
            "Build TurboTax, QuickBooks, or Credit Karma features. Intuit Bengaluru owns large portions of the product. Focus on AI-driven financial experiences.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── AI / ML Focused ───────────────────────────────────────────────────────
    {
        id: 21,
        employer_name: "Sarvam AI",
        employer_logo: "https://logo.clearbit.com/sarvam.ai",
        job_title: "ML Research Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://sarvam.ai/careers",
        job_posted_at: "2025-04-23",
        salary: "₹60,000/mo",
        tags: ["PyTorch", "Transformers", "Hindi NLP", "RLHF"],
        description:
            "Work on India's leading AI models for Indic languages. Help build speech, translation, and reasoning systems for Bharat. Ideal for ML/NLP enthusiasts.",
        is_fresher: true,
        is_remote: true,
        is_hot: true,
    },
    {
        id: 22,
        employer_name: "Krutrim",
        employer_logo: "https://logo.clearbit.com/olakrutrim.com",
        job_title: "AI/ML Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://krutrim.com/careers",
        job_posted_at: "2025-04-18",
        salary: "₹55,000/mo",
        tags: ["Python", "LLMs", "CUDA", "Fine-tuning"],
        description:
            "Ola's AI lab building India-first LLMs. Work on pre-training, RLHF, or inference optimization. Exciting early-stage environment with direct researcher access.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 23,
        employer_name: "Haptik",
        employer_logo: "https://logo.clearbit.com/haptik.ai",
        job_title: "NLP / Conversational AI Intern",
        job_city: "Mumbai",
        job_employment_type: "Internship",
        job_apply_link: "https://haptik.ai/careers",
        job_posted_at: "2025-04-15",
        salary: "₹45,000/mo",
        tags: ["Python", "spaCy", "Rasa", "GPT APIs"],
        description:
            "Build chatbot and voice assistant systems for enterprise clients. Work on intent classification, dialogue management, and LLM integration.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 24,
        employer_name: "Turing",
        employer_logo: "https://logo.clearbit.com/turing.com",
        job_title: "AI Trainer / Prompt Engineer Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://developers.turing.com",
        job_posted_at: "2025-04-20",
        salary: "₹30,000/mo",
        tags: ["Prompt Engineering", "Python", "LLMs", "Technical Writing"],
        description:
            "Evaluate and improve AI model outputs for code and reasoning tasks. Fully remote, flexible hours. Great entry point into the AI industry.",
        is_fresher: true,
        is_remote: true,
        is_hot: false,
    },

    // ─── DevOps / Cloud ─────────────────────────────────────────────────────────
    {
        id: 25,
        employer_name: "Infosys",
        employer_logo: "https://logo.clearbit.com/infosys.com",
        job_title: "Systems Engineer Trainee",
        job_city: "Bengaluru",
        job_employment_type: "Full-time (New Grad)",
        job_apply_link: "https://career.infosys.com/joblist",
        job_posted_at: "2025-04-22",
        salary: "₹3.6 LPA",
        tags: ["Java", "AWS", "DevOps", "Agile"],
        description:
            "Infosys InfyTQ pathway for freshers. Get trained on enterprise tech stack and deployed on client projects. Competitive stipend + PPO potential.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 26,
        employer_name: "Hashicorp",
        employer_logo: "https://logo.clearbit.com/hashicorp.com",
        job_title: "Software Engineer Intern (Platform)",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://www.hashicorp.com/jobs",
        job_posted_at: "2025-04-11",
        salary: "₹90,000/mo",
        tags: ["Go", "Terraform", "Vault", "Kubernetes"],
        description:
            "Work on Terraform, Vault, or Consul — the backbone of modern cloud infrastructure. Fully remote. Deep systems programming work. Ideal for Go enthusiasts.",
        is_fresher: true,
        is_remote: true,
        is_hot: false,
    },
    {
        id: 27,
        employer_name: "Hasura",
        employer_logo: "https://logo.clearbit.com/hasura.io",
        job_title: "Backend / GraphQL Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://hasura.io/careers",
        job_posted_at: "2025-04-08",
        salary: "₹50,000/mo",
        tags: ["Haskell", "Go", "GraphQL", "PostgreSQL"],
        description:
            "Build the open-source GraphQL engine used by 30k+ teams. Unusual stack (Haskell + Go). Perfect for candidates who love functional programming or OSS.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── EdTech ─────────────────────────────────────────────────────────────────
    {
        id: 28,
        employer_name: "BYJU'S",
        employer_logo: "https://logo.clearbit.com/byjus.com",
        job_title: "Software Developer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://byjus.com/careers",
        job_posted_at: "2025-04-04",
        salary: "₹40,000/mo",
        tags: ["React", "Node.js", "MongoDB", "Video Streaming"],
        description:
            "Work on learning platforms used by 150M+ students. Build adaptive learning algorithms, video delivery, or live class infrastructure.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 29,
        employer_name: "Unacademy",
        employer_logo: "https://logo.clearbit.com/unacademy.com",
        job_title: "Frontend Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://unacademy.com/careers",
        job_posted_at: "2025-04-07",
        salary: "₹45,000/mo",
        tags: ["React", "TypeScript", "WebRTC", "CSS"],
        description:
            "Build live class experiences, educator tools, and student dashboards. Unacademy's frontend team ships features used by millions preparing for competitive exams.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── Startups / High-Growth ─────────────────────────────────────────────────
    {
        id: 30,
        employer_name: "Postman",
        employer_logo: "https://logo.clearbit.com/postman.com",
        job_title: "Software Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://www.postman.com/company/careers/",
        job_posted_at: "2025-04-17",
        salary: "₹75,000/mo",
        tags: ["JavaScript", "Electron", "Node.js", "REST APIs"],
        description:
            "Build the tool used by 30M+ developers to design and test APIs. Postman is Bengaluru's most loved developer tool company. Work on core editor, collaboration, or CI/CD.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 31,
        employer_name: "BrowserStack",
        employer_logo: "https://logo.clearbit.com/browserstack.com",
        job_title: "SDE Intern (Testing Infrastructure)",
        job_city: "Mumbai",
        job_employment_type: "Internship",
        job_apply_link: "https://www.browserstack.com/careers",
        job_posted_at: "2025-04-14",
        salary: "₹65,000/mo",
        tags: ["Python", "Selenium", "Docker", "Kubernetes"],
        description:
            "Build the cloud testing infrastructure used by Netflix, Twitter, and Microsoft. Work on browser automation, device farms, or performance testing at massive scale.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 32,
        employer_name: "Chargebee",
        employer_logo: "https://logo.clearbit.com/chargebee.com",
        job_title: "Full Stack Intern",
        job_city: "Chennai",
        job_employment_type: "Internship",
        job_apply_link: "https://www.chargebee.com/jobs/",
        job_posted_at: "2025-04-09",
        salary: "₹50,000/mo",
        tags: ["Ruby on Rails", "React", "PostgreSQL", "Stripe API"],
        description:
            "Work on subscription billing software used by 6500+ SaaS companies. Chargebee is a Chennai startup that went global. Great for learning B2B SaaS product engineering.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 33,
        employer_name: "Darwinbox",
        employer_logo: "https://logo.clearbit.com/darwinbox.com",
        job_title: "Backend Intern (HR Tech)",
        job_city: "Hyderabad",
        job_employment_type: "Internship",
        job_apply_link: "https://darwinbox.com/us/life-at-darwinbox",
        job_posted_at: "2025-04-06",
        salary: "₹40,000/mo",
        tags: ["PHP", "Laravel", "MySQL", "REST APIs"],
        description:
            "India's fastest-growing HCM platform. Build payroll, attendance, and performance modules for enterprise clients. Good learning environment for backend-first developers.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 34,
        employer_name: "Setu",
        employer_logo: "https://logo.clearbit.com/setu.co",
        job_title: "API / Platform Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://setu.co/company/careers",
        job_posted_at: "2025-04-19",
        salary: "₹50,000/mo",
        tags: ["Python", "FastAPI", "UPI", "Banking APIs"],
        description:
            "Build financial infrastructure APIs (UPI, Account Aggregator, BBPS) that power India's fintech ecosystem. Deep exposure to RBI-regulated systems and open banking.",
        is_fresher: true,
        is_remote: false,
        is_hot: true,
    },
    {
        id: 35,
        employer_name: "Dukaan",
        employer_logo: "https://logo.clearbit.com/dukaan.io",
        job_title: "React Native Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://mydukaan.io/careers",
        job_posted_at: "2025-04-16",
        salary: "₹35,000/mo",
        tags: ["React Native", "JavaScript", "Firebase", "Shopify APIs"],
        description:
            "Build e-commerce apps for India's 60M+ small businesses. Fully remote. Dukaan moves fast — you'll ship features in your first week. Great for mobile-first developers.",
        is_fresher: true,
        is_remote: true,
        is_hot: false,
    },

    // ─── Cybersecurity / Infra ──────────────────────────────────────────────────
    {
        id: 36,
        employer_name: "Druva",
        employer_logo: "https://logo.clearbit.com/druva.com",
        job_title: "Cloud Security Intern",
        job_city: "Pune",
        job_employment_type: "Internship",
        job_apply_link: "https://www.druva.com/company/careers",
        job_posted_at: "2025-04-12",
        salary: "₹55,000/mo",
        tags: ["Python", "AWS", "IAM", "Golang"],
        description:
            "Work on data protection and security for cloud workloads. Druva is a Pune-based SaaS unicorn. Exposure to enterprise cloud security and compliance engineering.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 37,
        employer_name: "Palo Alto Networks",
        employer_logo: "https://logo.clearbit.com/paloaltonetworks.com",
        job_title: "Security Engineer Intern",
        job_city: "Bengaluru",
        job_employment_type: "Internship",
        job_apply_link: "https://jobs.paloaltonetworks.com/jobs",
        job_posted_at: "2025-04-05",
        salary: "₹95,000/mo",
        tags: ["C++", "Python", "Network Security", "SIEM"],
        description:
            "Work on next-gen firewall, SASE, or XDR products. Palo Alto's Bengaluru team does core security engineering. Ideal for candidates with a keen interest in cybersecurity.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── Data / Analytics ───────────────────────────────────────────────────────
    {
        id: 38,
        employer_name: "Clevertap",
        employer_logo: "https://logo.clearbit.com/clevertap.com",
        job_title: "Data Science Intern",
        job_city: "Mumbai",
        job_employment_type: "Internship",
        job_apply_link: "https://clevertap.com/careers/",
        job_posted_at: "2025-04-13",
        salary: "₹45,000/mo",
        tags: ["Python", "scikit-learn", "SQL", "A/B Testing"],
        description:
            "Build personalization and segmentation models for mobile marketing. CleverTap is a B2B SaaS company helping brands retain users. Good for ML + product analytics blend.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },
    {
        id: 39,
        employer_name: "Fractal Analytics",
        employer_logo: "https://logo.clearbit.com/fractal.ai",
        job_title: "Data Analyst Intern",
        job_city: "Mumbai",
        job_employment_type: "Internship",
        job_apply_link: "https://fractal.ai/careers/",
        job_posted_at: "2025-04-08",
        salary: "₹40,000/mo",
        tags: ["Python", "SQL", "Tableau", "Statistical Modeling"],
        description:
            "Work on analytics projects for Fortune 500 clients (FMCG, retail, banking). Fractal is one of India's top AI/analytics consultancies. Great for data-first careers.",
        is_fresher: true,
        is_remote: false,
        is_hot: false,
    },

    // ─── Remote / Global ────────────────────────────────────────────────────────
    {
        id: 40,
        employer_name: "Remote",
        employer_logo: "https://logo.clearbit.com/remote.com",
        job_title: "Software Engineer Intern (Global)",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://remote.com/careers",
        job_posted_at: "2025-04-21",
        salary: "₹70,000/mo",
        tags: ["Elixir", "React", "PostgreSQL", "Phoenix"],
        description:
            "Work on global HR and payroll infrastructure. Fully remote, async-first culture. Excellent exposure to distributed team workflows and global compliance engineering.",
        is_fresher: true,
        is_remote: true,
        is_hot: false,
    },
    {
        id: 41,
        employer_name: "Netlify",
        employer_logo: "https://logo.clearbit.com/netlify.com",
        job_title: "Frontend / DX Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://www.netlify.com/careers/",
        job_posted_at: "2025-04-18",
        salary: "₹80,000/mo",
        tags: ["JavaScript", "Next.js", "Edge Functions", "CDN"],
        description:
            "Build developer experience tooling for the Jamstack ecosystem. Work on deploy previews, analytics, or edge compute. Remote-first, globally distributed team.",
        is_fresher: true,
        is_remote: true,
        is_hot: false,
    },
    {
        id: 42,
        employer_name: "Linear",
        employer_logo: "https://logo.clearbit.com/linear.app",
        job_title: "Product Engineer Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://linear.app/careers",
        job_posted_at: "2025-04-15",
        salary: "₹1,00,000/mo",
        tags: ["TypeScript", "React", "Electron", "GraphQL"],
        description:
            "Work on the project management tool loved by the best engineering teams. Linear is obsessed with speed and design quality. Extremely high craft bar.",
        is_fresher: true,
        is_remote: true,
        is_hot: true,
    },
    {
        id: 43,
        employer_name: "Vercel",
        employer_logo: "https://logo.clearbit.com/vercel.com",
        job_title: "Infrastructure Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://vercel.com/careers",
        job_posted_at: "2025-04-12",
        salary: "₹1,10,000/mo",
        tags: ["Go", "Rust", "Edge Computing", "Kubernetes"],
        description:
            "Build the infrastructure that powers Next.js deployments for millions of developers. Work on edge networking, build systems, or observability. Fully remote.",
        is_fresher: false,
        is_remote: true,
        is_hot: true,
    },
    {
        id: 44,
        employer_name: "Supabase",
        employer_logo: "https://logo.clearbit.com/supabase.com",
        job_title: "Open Source Engineer Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://supabase.com/careers",
        job_posted_at: "2025-04-10",
        salary: "₹75,000/mo",
        tags: ["TypeScript", "PostgreSQL", "Rust", "Deno"],
        description:
            "Contribute to the open-source Firebase alternative. Work on realtime subscriptions, Auth, Storage, or Edge Functions. OSS-first culture, fully remote.",
        is_fresher: true,
        is_remote: true,
        is_hot: true,
    },
    {
        id: 45,
        employer_name: "Notion",
        employer_logo: "https://logo.clearbit.com/notion.so",
        job_title: "Software Engineer Intern",
        job_city: "Remote",
        job_employment_type: "Internship",
        job_apply_link: "https://www.notion.so/careers",
        job_posted_at: "2025-04-06",
        salary: "₹1,30,000/mo",
        tags: ["TypeScript", "React", "CRDTs", "Electron"],
        description:
            "Work on the all-in-one workspace tool used by 100M+ people. Notion interns work on editor internals, AI features, or API platform. High product quality bar.",
        is_fresher: true,
        is_remote: true,
        is_hot: true,
    },
];

// ─── Filter helpers ────────────────────────────────────────────────────────────

export const ALL_TAGS = [
    ...new Set(INTERNSHIPS.flatMap((j) => j.tags)),
].sort();

export const CITIES = [
    "All",
    ...new Set(INTERNSHIPS.map((j) => j.job_city)),
].sort();

export const JOB_TYPES = ["All", "Internship", "Full-time (New Grad)"];