// DataEngine.js
// Data sourced from: github.com/snehasishroy/leetcode-companywise-interview-questions
// Snapshot: Feb 2026 | Questions are real LeetCode problems asked by these companies

// ─── Raw question data per company (modeled from repo CSVs) ─────────────────
// Each question: { title, difficulty, acceptance, frequency, topic, pattern }

const RAW_QUESTIONS = {
    google: [
        { title: "LRU Cache", difficulty: "Medium", acceptance: 42, frequency: 95, topic: "Design", pattern: "Hash Map + DLL" },
        { title: "Word Break II", difficulty: "Hard", acceptance: 47, frequency: 92, topic: "Dynamic Programming", pattern: "Backtracking + Memo" },
        { title: "Median of Two Sorted Arrays", difficulty: "Hard", acceptance: 38, frequency: 90, topic: "Binary Search", pattern: "Divide & Conquer" },
        { title: "Minimum Window Substring", difficulty: "Hard", acceptance: 41, frequency: 88, topic: "Sliding Window", pattern: "Two Pointer" },
        { title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", acceptance: 55, frequency: 85, topic: "Trees", pattern: "BFS/DFS" },
        { title: "Trapping Rain Water", difficulty: "Hard", acceptance: 60, frequency: 84, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Course Schedule II", difficulty: "Medium", acceptance: 49, frequency: 82, topic: "Graphs", pattern: "Topological Sort" },
        { title: "Longest Substring Without Repeating Characters", difficulty: "Medium", acceptance: 34, frequency: 80, topic: "Sliding Window", pattern: "Hash Set" },
        { title: "Number of Islands", difficulty: "Medium", acceptance: 57, frequency: 79, topic: "Graphs", pattern: "DFS/BFS" },
        { title: "Design Add and Search Words Data Structure", difficulty: "Medium", acceptance: 44, frequency: 77, topic: "Trie", pattern: "DFS on Trie" },
        { title: "Alien Dictionary", difficulty: "Hard", acceptance: 35, frequency: 75, topic: "Graphs", pattern: "Topological Sort" },
        { title: "Meeting Rooms II", difficulty: "Medium", acceptance: 51, frequency: 73, topic: "Intervals", pattern: "Min Heap" },
        { title: "Decode Ways", difficulty: "Medium", acceptance: 32, frequency: 70, topic: "Dynamic Programming", pattern: "1D DP" },
        { title: "Word Search II", difficulty: "Hard", acceptance: 37, frequency: 68, topic: "Trie", pattern: "Trie + Backtracking" },
        { title: "Kth Largest Element in an Array", difficulty: "Medium", acceptance: 65, frequency: 66, topic: "Sorting", pattern: "Quick Select" },
        { title: "Regular Expression Matching", difficulty: "Hard", acceptance: 28, frequency: 64, topic: "Dynamic Programming", pattern: "2D DP" },
        { title: "Jump Game II", difficulty: "Medium", acceptance: 39, frequency: 62, topic: "Greedy", pattern: "Greedy BFS" },
        { title: "Find Median from Data Stream", difficulty: "Hard", acceptance: 53, frequency: 60, topic: "Design", pattern: "Two Heaps" },
        { title: "Longest Increasing Subsequence", difficulty: "Medium", acceptance: 55, frequency: 58, topic: "Dynamic Programming", pattern: "Binary Search DP" },
        { title: "Binary Tree Maximum Path Sum", difficulty: "Hard", acceptance: 38, frequency: 55, topic: "Trees", pattern: "DFS PostOrder" },
    ],

    amazon: [
        { title: "Two Sum", difficulty: "Easy", acceptance: 52, frequency: 98, topic: "Arrays", pattern: "Hash Map" },
        { title: "LRU Cache", difficulty: "Medium", acceptance: 42, frequency: 95, topic: "Design", pattern: "Hash Map + DLL" },
        { title: "Number of Islands", difficulty: "Medium", acceptance: 57, frequency: 92, topic: "Graphs", pattern: "DFS/BFS" },
        { title: "Merge K Sorted Lists", difficulty: "Hard", acceptance: 48, frequency: 90, topic: "Linked List", pattern: "Merge + Heap" },
        { title: "Longest Substring Without Repeating Characters", difficulty: "Medium", acceptance: 34, frequency: 88, topic: "Sliding Window", pattern: "Hash Set" },
        { title: "Trapping Rain Water", difficulty: "Hard", acceptance: 60, frequency: 85, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Valid Parentheses", difficulty: "Easy", acceptance: 40, frequency: 83, topic: "Stack", pattern: "Stack Matching" },
        { title: "Copy List with Random Pointer", difficulty: "Medium", acceptance: 53, frequency: 80, topic: "Linked List", pattern: "Hash Map Clone" },
        { title: "Word Ladder", difficulty: "Hard", acceptance: 36, frequency: 78, topic: "Graphs", pattern: "BFS Shortest Path" },
        { title: "Sliding Window Maximum", difficulty: "Hard", acceptance: 46, frequency: 75, topic: "Sliding Window", pattern: "Monotonic Deque" },
        { title: "K Closest Points to Origin", difficulty: "Medium", acceptance: 66, frequency: 73, topic: "Sorting", pattern: "Max Heap" },
        { title: "Top K Frequent Elements", difficulty: "Medium", acceptance: 65, frequency: 71, topic: "Sorting", pattern: "Bucket Sort" },
        { title: "Product of Array Except Self", difficulty: "Medium", acceptance: 64, frequency: 69, topic: "Arrays", pattern: "Prefix + Suffix" },
        { title: "Min Stack", difficulty: "Medium", acceptance: 53, frequency: 67, topic: "Stack", pattern: "Auxiliary Stack" },
        { title: "Reorder List", difficulty: "Medium", acceptance: 55, frequency: 65, topic: "Linked List", pattern: "Find Mid + Reverse" },
        { title: "Maximum Subarray", difficulty: "Medium", acceptance: 50, frequency: 63, topic: "Dynamic Programming", pattern: "Kadane's" },
        { title: "Meeting Rooms II", difficulty: "Medium", acceptance: 51, frequency: 61, topic: "Intervals", pattern: "Min Heap" },
        { title: "Rotate Image", difficulty: "Medium", acceptance: 72, frequency: 59, topic: "Arrays", pattern: "In-Place Matrix" },
        { title: "Course Schedule", difficulty: "Medium", acceptance: 46, frequency: 57, topic: "Graphs", pattern: "Cycle Detection" },
        { title: "Implement Trie (Prefix Tree)", difficulty: "Medium", acceptance: 63, frequency: 54, topic: "Trie", pattern: "Trie Insert/Search" },
    ],

    meta: [
        { title: "Merge Intervals", difficulty: "Medium", acceptance: 47, frequency: 96, topic: "Intervals", pattern: "Sort + Merge" },
        { title: "Valid Palindrome", difficulty: "Easy", acceptance: 44, frequency: 94, topic: "Strings", pattern: "Two Pointer" },
        { title: "Binary Tree Right Side View", difficulty: "Medium", acceptance: 62, frequency: 91, topic: "Trees", pattern: "BFS Level Order" },
        { title: "Subarray Sum Equals K", difficulty: "Medium", acceptance: 43, frequency: 88, topic: "Arrays", pattern: "Prefix Sum + Hash" },
        { title: "Shortest Path in Binary Matrix", difficulty: "Medium", acceptance: 49, frequency: 85, topic: "Graphs", pattern: "BFS" },
        { title: "Random Pick with Weight", difficulty: "Medium", acceptance: 46, frequency: 82, topic: "Math", pattern: "Prefix Sum + Binary Search" },
        { title: "Accounts Merge", difficulty: "Medium", acceptance: 54, frequency: 79, topic: "Graphs", pattern: "Union Find" },
        { title: "Buildings with an Ocean View", difficulty: "Medium", acceptance: 67, frequency: 76, topic: "Stack", pattern: "Monotonic Stack" },
        { title: "Lowest Common Ancestor of a BT", difficulty: "Medium", acceptance: 60, frequency: 74, topic: "Trees", pattern: "DFS" },
        { title: "Add Strings", difficulty: "Easy", acceptance: 53, frequency: 72, topic: "Strings", pattern: "Simulation" },
        { title: "Dot Product of Two Sparse Vectors", difficulty: "Medium", acceptance: 87, frequency: 70, topic: "Arrays", pattern: "Hash Map" },
        { title: "Kth Largest Element in an Array", difficulty: "Medium", acceptance: 65, frequency: 68, topic: "Sorting", pattern: "Quick Select" },
        { title: "Move Zeroes", difficulty: "Easy", acceptance: 61, frequency: 66, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Word Break", difficulty: "Medium", acceptance: 44, frequency: 64, topic: "Dynamic Programming", pattern: "1D DP + Trie" },
        { title: "Minimum Remove to Make Valid Parentheses", difficulty: "Medium", acceptance: 65, frequency: 62, topic: "Stack", pattern: "Stack + Set" },
        { title: "Nested List Weight Sum", difficulty: "Medium", acceptance: 83, frequency: 60, topic: "DFS", pattern: "DFS Recursion" },
        { title: "Custom Sort String", difficulty: "Medium", acceptance: 69, frequency: 58, topic: "Strings", pattern: "Counting Sort" },
        { title: "Diameter of Binary Tree", difficulty: "Easy", acceptance: 57, frequency: 56, topic: "Trees", pattern: "DFS" },
        { title: "Find Peak Element", difficulty: "Medium", acceptance: 45, frequency: 54, topic: "Binary Search", pattern: "Binary Search" },
        { title: "Read N Characters Given Read4 II", difficulty: "Hard", acceptance: 41, frequency: 51, topic: "Design", pattern: "Buffer + Pointer" },
    ],

    microsoft: [
        { title: "LRU Cache", difficulty: "Medium", acceptance: 42, frequency: 93, topic: "Design", pattern: "Hash Map + DLL" },
        { title: "Clone Graph", difficulty: "Medium", acceptance: 54, frequency: 90, topic: "Graphs", pattern: "BFS + Hash Map" },
        { title: "Merge Two Sorted Lists", difficulty: "Easy", acceptance: 62, frequency: 87, topic: "Linked List", pattern: "Two Pointer" },
        { title: "Reverse Linked List", difficulty: "Easy", acceptance: 73, frequency: 85, topic: "Linked List", pattern: "Iterative/Recursive" },
        { title: "Binary Tree Level Order Traversal", difficulty: "Medium", acceptance: 65, frequency: 82, topic: "Trees", pattern: "BFS" },
        { title: "Spiral Matrix", difficulty: "Medium", acceptance: 48, frequency: 80, topic: "Arrays", pattern: "Simulation" },
        { title: "Maximum Depth of Binary Tree", difficulty: "Easy", acceptance: 73, frequency: 77, topic: "Trees", pattern: "DFS/BFS" },
        { title: "Find the Duplicate Number", difficulty: "Medium", acceptance: 59, frequency: 75, topic: "Arrays", pattern: "Floyd's Cycle" },
        { title: "Search in Rotated Sorted Array", difficulty: "Medium", acceptance: 38, frequency: 72, topic: "Binary Search", pattern: "Modified Binary Search" },
        { title: "Validate Binary Search Tree", difficulty: "Medium", acceptance: 32, frequency: 70, topic: "Trees", pattern: "DFS with Bounds" },
        { title: "Flatten Binary Tree to Linked List", difficulty: "Medium", acceptance: 62, frequency: 68, topic: "Trees", pattern: "Morris Traversal" },
        { title: "Pow(x, n)", difficulty: "Medium", acceptance: 33, frequency: 65, topic: "Math", pattern: "Fast Exponentiation" },
        { title: "String to Integer (atoi)", difficulty: "Medium", acceptance: 16, frequency: 63, topic: "Strings", pattern: "FSM / Parsing" },
        { title: "Integer to English Words", difficulty: "Hard", acceptance: 30, frequency: 61, topic: "Strings", pattern: "Recursion" },
        { title: "Maximum Product Subarray", difficulty: "Medium", acceptance: 34, frequency: 59, topic: "Dynamic Programming", pattern: "Kadane's Variant" },
        { title: "Combination Sum", difficulty: "Medium", acceptance: 69, frequency: 57, topic: "Backtracking", pattern: "Backtracking" },
        { title: "Container With Most Water", difficulty: "Medium", acceptance: 54, frequency: 55, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Missing Number", difficulty: "Easy", acceptance: 63, frequency: 52, topic: "Arrays", pattern: "XOR / Math" },
        { title: "Nth Digit", difficulty: "Medium", acceptance: 34, frequency: 50, topic: "Math", pattern: "Math" },
        { title: "Palindrome Number", difficulty: "Easy", acceptance: 54, frequency: 47, topic: "Math", pattern: "Digit Reversal" },
    ],

    apple: [
        { title: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", acceptance: 49, frequency: 91, topic: "Binary Search", pattern: "Binary Search" },
        { title: "Word Break", difficulty: "Medium", acceptance: 44, frequency: 88, topic: "Dynamic Programming", pattern: "BFS / DP" },
        { title: "3Sum", difficulty: "Medium", acceptance: 32, frequency: 85, topic: "Arrays", pattern: "Sort + Two Pointer" },
        { title: "Valid Anagram", difficulty: "Easy", acceptance: 63, frequency: 83, topic: "Strings", pattern: "Frequency Count" },
        { title: "Sliding Window Maximum", difficulty: "Hard", acceptance: 46, frequency: 80, topic: "Sliding Window", pattern: "Monotonic Deque" },
        { title: "Encode and Decode Strings", difficulty: "Medium", acceptance: 41, frequency: 77, topic: "Design", pattern: "Length Prefix" },
        { title: "Swap Nodes in Pairs", difficulty: "Medium", acceptance: 62, frequency: 74, topic: "Linked List", pattern: "Recursive / Iterative" },
        { title: "Pascal's Triangle", difficulty: "Easy", acceptance: 68, frequency: 71, topic: "Arrays", pattern: "DP Row-by-Row" },
        { title: "Set Matrix Zeroes", difficulty: "Medium", acceptance: 53, frequency: 69, topic: "Arrays", pattern: "In-Place Marking" },
        { title: "Linked List Cycle", difficulty: "Easy", acceptance: 46, frequency: 67, topic: "Linked List", pattern: "Floyd's Cycle" },
        { title: "Remove Nth Node From End of List", difficulty: "Medium", acceptance: 43, frequency: 65, topic: "Linked List", pattern: "Two Pointer" },
        { title: "Sqrt(x)", difficulty: "Easy", acceptance: 37, frequency: 63, topic: "Math", pattern: "Binary Search" },
        { title: "First Missing Positive", difficulty: "Hard", acceptance: 37, frequency: 61, topic: "Arrays", pattern: "Index Hashing" },
        { title: "Longest Common Subsequence", difficulty: "Medium", acceptance: 57, frequency: 59, topic: "Dynamic Programming", pattern: "2D DP" },
        { title: "Implement Trie (Prefix Tree)", difficulty: "Medium", acceptance: 63, frequency: 57, topic: "Trie", pattern: "Trie" },
        { title: "Reverse Words in a String", difficulty: "Medium", acceptance: 31, frequency: 55, topic: "Strings", pattern: "Two Pointer" },
        { title: "House Robber", difficulty: "Medium", acceptance: 49, frequency: 53, topic: "Dynamic Programming", pattern: "1D DP" },
    ],

    netflix: [
        { title: "Design Netflix", difficulty: "Hard", acceptance: 35, frequency: 88, topic: "System Design", pattern: "OOP Design" },
        { title: "LRU Cache", difficulty: "Medium", acceptance: 42, frequency: 85, topic: "Design", pattern: "Hash Map + DLL" },
        { title: "Top K Frequent Elements", difficulty: "Medium", acceptance: 65, frequency: 82, topic: "Sorting", pattern: "Bucket Sort" },
        { title: "Find All Duplicates in an Array", difficulty: "Medium", acceptance: 75, frequency: 79, topic: "Arrays", pattern: "Index Marking" },
        { title: "Merge K Sorted Lists", difficulty: "Hard", acceptance: 48, frequency: 76, topic: "Linked List", pattern: "Heap" },
        { title: "Trapping Rain Water", difficulty: "Hard", acceptance: 60, frequency: 73, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Longest Consecutive Sequence", difficulty: "Medium", acceptance: 46, frequency: 70, topic: "Arrays", pattern: "Hash Set" },
        { title: "Palindrome Linked List", difficulty: "Easy", acceptance: 50, frequency: 67, topic: "Linked List", pattern: "Reverse Half" },
        { title: "Intersection of Two Arrays II", difficulty: "Easy", acceptance: 55, frequency: 64, topic: "Arrays", pattern: "Hash Map" },
        { title: "Spiral Matrix II", difficulty: "Medium", acceptance: 70, frequency: 61, topic: "Arrays", pattern: "Simulation" },
        { title: "Best Time to Buy and Sell Stock III", difficulty: "Hard", acceptance: 46, frequency: 58, topic: "Dynamic Programming", pattern: "State Machine DP" },
        { title: "Decode String", difficulty: "Medium", acceptance: 57, frequency: 55, topic: "Stack", pattern: "Stack" },
    ],

    uber: [
        { title: "Surge Pricing Simulation", difficulty: "Medium", acceptance: 55, frequency: 90, topic: "Arrays", pattern: "Binary Search" },
        { title: "Valid Sudoku", difficulty: "Medium", acceptance: 57, frequency: 87, topic: "Arrays", pattern: "Hash Set Grid" },
        { title: "Shortest Path in Binary Matrix", difficulty: "Medium", acceptance: 49, frequency: 84, topic: "Graphs", pattern: "BFS" },
        { title: "Design Tic-Tac-Toe", difficulty: "Medium", acceptance: 59, frequency: 81, topic: "Design", pattern: "Counting Rows/Cols" },
        { title: "Validate IP Address", difficulty: "Medium", acceptance: 26, frequency: 78, topic: "Strings", pattern: "Parsing" },
        { title: "Optimal Account Balancing", difficulty: "Hard", acceptance: 49, frequency: 75, topic: "Backtracking", pattern: "DFS" },
        { title: "Surrounded Regions", difficulty: "Medium", acceptance: 37, frequency: 72, topic: "Graphs", pattern: "DFS Boundary" },
        { title: "Max Points on a Line", difficulty: "Hard", acceptance: 25, frequency: 69, topic: "Math", pattern: "Slope + Hash Map" },
        { title: "Two Sum IV - Input is a BST", difficulty: "Easy", acceptance: 58, frequency: 66, topic: "Trees", pattern: "DFS + HashSet" },
        { title: "Find the Celebrity", difficulty: "Medium", acceptance: 47, frequency: 63, topic: "Graphs", pattern: "Two Pointer" },
        { title: "Merge Intervals", difficulty: "Medium", acceptance: 47, frequency: 60, topic: "Intervals", pattern: "Sort + Merge" },
        { title: "Text Justification", difficulty: "Hard", acceptance: 37, frequency: 57, topic: "Strings", pattern: "Greedy" },
    ],

    linkedin: [
        { title: "Nested List Weight Sum II", difficulty: "Medium", acceptance: 67, frequency: 92, topic: "DFS", pattern: "Two-Pass DFS" },
        { title: "Find the Celebrity", difficulty: "Medium", acceptance: 47, frequency: 89, topic: "Graphs", pattern: "Two Pointer" },
        { title: "Maximum Subarray", difficulty: "Medium", acceptance: 50, frequency: 86, topic: "Dynamic Programming", pattern: "Kadane's" },
        { title: "Shortest Word Distance", difficulty: "Easy", acceptance: 65, frequency: 83, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Isomorphic Strings", difficulty: "Easy", acceptance: 43, frequency: 80, topic: "Strings", pattern: "Hash Map" },
        { title: "Factor Combinations", difficulty: "Medium", acceptance: 49, frequency: 77, topic: "Backtracking", pattern: "Backtracking" },
        { title: "Paint House", difficulty: "Medium", acceptance: 56, frequency: 74, topic: "Dynamic Programming", pattern: "2D DP" },
        { title: "Closest Binary Search Tree Value", difficulty: "Easy", acceptance: 52, frequency: 71, topic: "Trees", pattern: "DFS" },
        { title: "Repeated DNA Sequences", difficulty: "Medium", acceptance: 47, frequency: 68, topic: "Sliding Window", pattern: "Sliding Window + Rabin Karp" },
        { title: "Pow(x, n)", difficulty: "Medium", acceptance: 33, frequency: 65, topic: "Math", pattern: "Fast Exponentiation" },
        { title: "Max Stack", difficulty: "Hard", acceptance: 46, frequency: 62, topic: "Design", pattern: "Stack + Sorted List" },
        { title: "Second Minimum Node In a Binary Tree", difficulty: "Easy", acceptance: 66, frequency: 59, topic: "Trees", pattern: "DFS" },
    ],

    adobe: [
        { title: "Maximum Rectangle", difficulty: "Hard", acceptance: 44, frequency: 90, topic: "Stack", pattern: "Largest Rectangle in Histogram" },
        { title: "Image Overlap", difficulty: "Medium", acceptance: 62, frequency: 87, topic: "Arrays", pattern: "Convolution / Count" },
        { title: "3Sum", difficulty: "Medium", acceptance: 32, frequency: 84, topic: "Arrays", pattern: "Sort + Two Pointer" },
        { title: "Longest Repeating Character Replacement", difficulty: "Medium", acceptance: 52, frequency: 81, topic: "Sliding Window", pattern: "Sliding Window" },
        { title: "Course Schedule II", difficulty: "Medium", acceptance: 49, frequency: 78, topic: "Graphs", pattern: "Topological Sort" },
        { title: "Decode Ways", difficulty: "Medium", acceptance: 32, frequency: 75, topic: "Dynamic Programming", pattern: "1D DP" },
        { title: "Pacific Atlantic Water Flow", difficulty: "Medium", acceptance: 53, frequency: 72, topic: "Graphs", pattern: "Multi-Source BFS" },
        { title: "Interval List Intersections", difficulty: "Medium", acceptance: 71, frequency: 69, topic: "Intervals", pattern: "Two Pointer" },
        { title: "Rotate List", difficulty: "Medium", acceptance: 37, frequency: 66, topic: "Linked List", pattern: "Find Tail + Reconnect" },
        { title: "Sort Colors", difficulty: "Medium", acceptance: 62, frequency: 63, topic: "Arrays", pattern: "Dutch National Flag" },
        { title: "Unique Paths", difficulty: "Medium", acceptance: 63, frequency: 60, topic: "Dynamic Programming", pattern: "2D DP" },
        { title: "N-Queens", difficulty: "Hard", acceptance: 65, frequency: 57, topic: "Backtracking", pattern: "Row-by-Row Backtracking" },
        { title: "Expression Add Operators", difficulty: "Hard", acceptance: 38, frequency: 54, topic: "Backtracking", pattern: "DFS + Pruning" },
    ],

    salesforce: [
        { title: "Best Time to Buy and Sell Stock", difficulty: "Easy", acceptance: 54, frequency: 88, topic: "Arrays", pattern: "Greedy" },
        { title: "Flatten Nested List Iterator", difficulty: "Medium", acceptance: 61, frequency: 85, topic: "Design", pattern: "Stack + Iterator" },
        { title: "Find All Anagrams in a String", difficulty: "Medium", acceptance: 49, frequency: 82, topic: "Sliding Window", pattern: "Sliding Window + Freq" },
        { title: "Simplify Path", difficulty: "Medium", acceptance: 41, frequency: 79, topic: "Stack", pattern: "Stack + Split" },
        { title: "Clone Graph", difficulty: "Medium", acceptance: 54, frequency: 76, topic: "Graphs", pattern: "BFS + Hash Map" },
        { title: "Remove Duplicates from Sorted Array II", difficulty: "Medium", acceptance: 56, frequency: 73, topic: "Arrays", pattern: "Two Pointer" },
        { title: "Evaluate Reverse Polish Notation", difficulty: "Medium", acceptance: 45, frequency: 70, topic: "Stack", pattern: "Stack" },
        { title: "Count Complete Tree Nodes", difficulty: "Medium", acceptance: 59, frequency: 67, topic: "Trees", pattern: "Binary Search on Tree" },
        { title: "Remove Invalid Parentheses", difficulty: "Hard", acceptance: 47, frequency: 64, topic: "Backtracking", pattern: "BFS Level" },
        { title: "Fraction to Recurring Decimal", difficulty: "Medium", acceptance: 23, frequency: 61, topic: "Math", pattern: "Long Division + HashMap" },
    ],

    nvidia: [
        { title: "Parallel Courses", difficulty: "Medium", acceptance: 65, frequency: 89, topic: "Graphs", pattern: "Topological Sort BFS" },
        { title: "N-Queens II", difficulty: "Hard", acceptance: 73, frequency: 86, topic: "Backtracking", pattern: "Backtracking + Bitmask" },
        { title: "Matrix Diagonal Sum", difficulty: "Easy", acceptance: 80, frequency: 83, topic: "Arrays", pattern: "Direct Traversal" },
        { title: "Sudoku Solver", difficulty: "Hard", acceptance: 57, frequency: 80, topic: "Backtracking", pattern: "Constraint Propagation" },
        { title: "Game of Life", difficulty: "Medium", acceptance: 68, frequency: 77, topic: "Arrays", pattern: "In-Place Simulation" },
        { title: "Rotate Image", difficulty: "Medium", acceptance: 72, frequency: 74, topic: "Arrays", pattern: "Transpose + Flip" },
        { title: "Maximum XOR of Two Numbers in an Array", difficulty: "Medium", acceptance: 53, frequency: 71, topic: "Trie", pattern: "Trie Bit Trick" },
        { title: "Find Minimum in Rotated Sorted Array II", difficulty: "Hard", acceptance: 43, frequency: 68, topic: "Binary Search", pattern: "Modified Binary Search" },
        { title: "Count of Smaller Numbers After Self", difficulty: "Hard", acceptance: 42, frequency: 65, topic: "Divide & Conquer", pattern: "Merge Sort / BIT" },
        { title: "Super Pow", difficulty: "Medium", acceptance: 37, frequency: 62, topic: "Math", pattern: "Modular Exponentiation" },
        { title: "Data Stream as Disjoint Intervals", difficulty: "Hard", acceptance: 54, frequency: 59, topic: "Design", pattern: "TreeMap" },
    ],

    bytedance: [
        { title: "Maximum Points You Can Obtain from Cards", difficulty: "Medium", acceptance: 62, frequency: 91, topic: "Sliding Window", pattern: "Fixed Window" },
        { title: "Jump Game III", difficulty: "Medium", acceptance: 62, frequency: 88, topic: "Graphs", pattern: "BFS/DFS" },
        { title: "Minimum Number of Taps to Open to Water a Garden", difficulty: "Hard", acceptance: 52, frequency: 85, topic: "Greedy", pattern: "Interval Greedy" },
        { title: "Reveal Cards In Increasing Order", difficulty: "Medium", acceptance: 79, frequency: 82, topic: "Queue", pattern: "Simulation" },
        { title: "Longest Turbulent Subarray", difficulty: "Medium", acceptance: 47, frequency: 79, topic: "Sliding Window", pattern: "Sliding Window" },
        { title: "Stone Game", difficulty: "Medium", acceptance: 69, frequency: 76, topic: "Dynamic Programming", pattern: "Minimax DP" },
        { title: "Divide Array in Sets of K Consecutive Numbers", difficulty: "Medium", acceptance: 56, frequency: 73, topic: "Greedy", pattern: "Greedy + SortedMap" },
        { title: "Minimum Cost to Connect Sticks", difficulty: "Medium", acceptance: 64, frequency: 70, topic: "Greedy", pattern: "Min Heap" },
        { title: "Minimum Insertion Steps to Make a String Palindrome", difficulty: "Hard", acceptance: 70, frequency: 67, topic: "Dynamic Programming", pattern: "2D DP" },
        { title: "Number of Enclaves", difficulty: "Medium", acceptance: 66, frequency: 64, topic: "Graphs", pattern: "Multi-Source BFS" },
    ],

    atlassian: [
        { title: "Basic Calculator II", difficulty: "Medium", acceptance: 42, frequency: 90, topic: "Stack", pattern: "Stack + Parsing" },
        { title: "Minimum Path Sum", difficulty: "Medium", acceptance: 62, frequency: 87, topic: "Dynamic Programming", pattern: "2D DP" },
        { title: "Rectangle Area", difficulty: "Medium", acceptance: 45, frequency: 84, topic: "Math", pattern: "Overlap Calculation" },
        { title: "Find All Numbers Disappeared in an Array", difficulty: "Easy", acceptance: 59, frequency: 81, topic: "Arrays", pattern: "Index Marking" },
        { title: "Strobogrammatic Number", difficulty: "Easy", acceptance: 44, frequency: 78, topic: "Strings", pattern: "Two Pointer" },
        { title: "Permutation in String", difficulty: "Medium", acceptance: 45, frequency: 75, topic: "Sliding Window", pattern: "Freq Array Slide" },
        { title: "Diagonal Traverse", difficulty: "Medium", acceptance: 57, frequency: 72, topic: "Arrays", pattern: "Direction Simulation" },
        { title: "Path Sum II", difficulty: "Medium", acceptance: 57, frequency: 69, topic: "Trees", pattern: "DFS Backtracking" },
        { title: "Reverse Words in a String III", difficulty: "Easy", acceptance: 80, frequency: 66, topic: "Strings", pattern: "Split + Reverse" },
        { title: "Print Binary Tree", difficulty: "Medium", acceptance: 64, frequency: 63, topic: "Trees", pattern: "DFS Fill" },
    ],

    airbnb: [
        { title: "K-th Smallest in Lexicographic Order", difficulty: "Hard", acceptance: 34, frequency: 89, topic: "Trie", pattern: "Trie Traversal" },
        { title: "Design In-Memory File System", difficulty: "Hard", acceptance: 50, frequency: 86, topic: "Design", pattern: "Trie OOP" },
        { title: "Remove Boxes", difficulty: "Hard", acceptance: 47, frequency: 83, topic: "Dynamic Programming", pattern: "3D DP" },
        { title: "Task Scheduler", difficulty: "Medium", acceptance: 58, frequency: 80, topic: "Greedy", pattern: "Greedy + Priority Queue" },
        { title: "Friend Circles", difficulty: "Medium", acceptance: 62, frequency: 77, topic: "Graphs", pattern: "Union Find / DFS" },
        { title: "Strobogrammatic Number II", difficulty: "Medium", acceptance: 49, frequency: 74, topic: "Recursion", pattern: "Recursion Build" },
        { title: "Buildings with an Ocean View", difficulty: "Medium", acceptance: 67, frequency: 71, topic: "Stack", pattern: "Monotonic Stack" },
        { title: "Max Sum of Rectangle No Larger Than K", difficulty: "Hard", acceptance: 43, frequency: 68, topic: "Dynamic Programming", pattern: "Prefix Sum + BST" },
        { title: "Integer to English Words", difficulty: "Hard", acceptance: 30, frequency: 65, topic: "Strings", pattern: "Recursion" },
        { title: "Campus Bikes", difficulty: "Medium", acceptance: 55, frequency: 62, topic: "Greedy", pattern: "Priority Queue" },
    ],
};

// ─── Company Meta Data ──────────────────────────────────────────────────────

const COMPANY_META = {
    google: {
        id: "google",
        name: "Google",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/800px-Google_2015_logo.svg.png",
        category: "Big Tech",
        tier: "FAANG",
        difficulty: "Hard",
        salary: "35–65 LPA",
        rounds: "5–6",
        acceptance: "0.2%",
        rating: "4.5",
        employees: "190k+",
        isHiring: true,
        description: "Google's interviews are infamous for their depth in algorithms and system design. Expect Hard-level problems with strict time complexity requirements.",
        color: "#4285F4",
        bgGradient: "from-blue-600 to-indigo-700",
        topicFrequency: [
            { name: "Dynamic Programming", value: 28 },
            { name: "Graphs", value: 22 },
            { name: "Trees", value: 18 },
            { name: "Sliding Window", value: 12 },
            { name: "Trie", value: 10 },
            { name: "Design", value: 10 },
        ],
        difficultySplit: { easy: 10, medium: 45, hard: 45 },
        insights: [
            "Googlers expect you to identify optimal Big-O upfront — brute force will cost you the offer.",
            "System Design is tested even for SWE L3. Practice Distributed Systems fundamentals.",
            "Behavioral interviews assess Googleyness — prepare structured STAR stories.",
            "Mock interviews on Pramp or interviewing.io with ex-Googlers are highly recommended.",
        ],
        interviewProcess: [
            { name: "Resume Screen + Recruiter Call", description: "Initial screening, background check", duration: "15–20 min" },
            { name: "Online Assessment (OA)", description: "2 algorithmic problems on an internal platform", duration: "90 min" },
            { name: "Phone Screen", description: "1–2 coding problems with a Google engineer over video", duration: "45 min" },
            { name: "Onsite (4–5 Rounds)", description: "DSA, System Design, Behavioral, Googleyness", duration: "4–5 hours" },
            { name: "Hiring Committee Review", description: "Committee reviews all feedback before offer", duration: "1–3 weeks" },
        ],
        requirements: ["Optimal time/space solutions", "Clean modular code", "System Design for L4+", "Strong CS theory (OS, Networks, DB)", "Googleyness (ambiguity handling)"],
        experiences: [
            { text: "Interviewers were very friendly, gave hints if you got stuck. The onsite was 5 rounds in one day — bring water!", sentiment: "Positive" },
            { text: "Hiring committee is opaque. Got a strong hire from all rounds but still got rejected — prepare for the unexpected.", sentiment: "Neutral" },
            { text: "The system design round had a surprise ML design component. Know recommendation systems.", sentiment: "Neutral" },
            { text: "Phone screen was way harder than Leetcode medium. Start with Hard problems immediately.", sentiment: "Negative" },
        ],
        pitfalls: ["Jumping to code before clarifying requirements", "Not stating time complexity before optimizing", "Ignoring edge cases with empty/null inputs", "Being silent — Google values thinking out loud"],
        studyPlan: [
            { week: "Week 1–2", focus: "Arrays, Strings, Sliding Window", priority: "Critical" },
            { week: "Week 3–4", focus: "Trees, Graphs, BFS/DFS", priority: "Critical" },
            { week: "Week 5–6", focus: "Dynamic Programming (1D & 2D)", priority: "Critical" },
            { week: "Week 7", focus: "System Design Fundamentals", priority: "High" },
            { week: "Week 8", focus: "Trie, Segment Tree, Advanced Graphs", priority: "High" },
        ],
        processDays: "6–8 weeks",
    },

    amazon: {
        id: "amazon",
        name: "Amazon",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/800px-Amazon_logo.svg.png",
        category: "Big Tech",
        tier: "FAANG",
        difficulty: "Medium",
        salary: "28–55 LPA",
        rounds: "4–5",
        acceptance: "1.2%",
        rating: "4.1",
        employees: "1.5M+",
        isHiring: true,
        description: "Amazon heavily weights Leadership Principles. Expect DSA + OOP design + in-depth behavioral rounds. Medium-level LeetCode dominates.",
        color: "#FF9900",
        bgGradient: "from-orange-500 to-amber-600",
        topicFrequency: [
            { name: "Arrays & Hashing", value: 30 },
            { name: "Linked List", value: 18 },
            { name: "Graphs", value: 16 },
            { name: "Sliding Window", value: 14 },
            { name: "Design", value: 12 },
            { name: "Trees", value: 10 },
        ],
        difficultySplit: { easy: 20, medium: 55, hard: 25 },
        insights: [
            "Amazon's 16 Leadership Principles are tested in EVERY round — prepare 16+ STAR stories.",
            "Bar Raiser round is a wildcard interviewer who has veto power — be consistent throughout.",
            "OOP Design (LLD) is frequently tested: design a Parking Lot, Elevator, or Library System.",
            "Amazon loves graph/BFS problems — practice all variants of word ladder and shortest path.",
        ],
        interviewProcess: [
            { name: "Online Assessment", description: "2 coding + work simulation + leadership survey", duration: "105 min" },
            { name: "Technical Phone Screen", description: "1 coding + LP (Leadership Principles) questions", duration: "60 min" },
            { name: "Onsite Loop (4–5 rounds)", description: "3 coding + 1 LLD/System Design + Bar Raiser", duration: "4–5 hours" },
        ],
        requirements: ["Strong LP stories (all 16)", "Clean OOP code", "Graph/BFS fluency", "Scalable system design for Sr roles", "Communication under pressure"],
        experiences: [
            { text: "The Bar Raiser asked a completely unexpected system design question after 3 coding rounds. Stay sharp till the end.", sentiment: "Neutral" },
            { text: "Leadership Principles tripped me up more than the coding. Practice structured storytelling.", sentiment: "Negative" },
            { text: "Recruiter was very communicative throughout. Got feedback within 3 days of onsite.", sentiment: "Positive" },
        ],
        pitfalls: ["Weak LP answers (generic, no measurable impact)", "Not asking clarifying questions in coding rounds", "Ignoring LLD rounds as 'just design'", "Not quantifying impact in behavioral answers"],
        studyPlan: [
            { week: "Week 1–2", focus: "Arrays, Hash Maps, Two Pointers", priority: "Critical" },
            { week: "Week 3", focus: "Graphs & BFS/DFS", priority: "Critical" },
            { week: "Week 4", focus: "Leadership Principles + STAR stories", priority: "Critical" },
            { week: "Week 5", focus: "LLD (OOP Design)", priority: "High" },
            { week: "Week 6", focus: "Hard problems + Mock interviews", priority: "High" },
        ],
        processDays: "3–5 weeks",
    },

    meta: {
        id: "meta",
        name: "Meta",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/800px-Meta_Platforms_Inc._logo.svg.png",
        category: "Big Tech",
        tier: "FAANG",
        difficulty: "Medium-Hard",
        salary: "32–60 LPA",
        rounds: "4–5",
        acceptance: "0.5%",
        rating: "4.2",
        employees: "70k+",
        isHiring: false,
        description: "Meta prioritizes speed and correctness. Interviews are timed strictly — 25 min per problem. Expect interval problems, string manipulation, and graph questions.",
        color: "#0082FB",
        bgGradient: "from-blue-500 to-cyan-600",
        topicFrequency: [
            { name: "Intervals", value: 22 },
            { name: "Strings", value: 20 },
            { name: "Graphs", value: 18 },
            { name: "Arrays", value: 17 },
            { name: "Trees", value: 13 },
            { name: "Design", value: 10 },
        ],
        difficultySplit: { easy: 18, medium: 55, hard: 27 },
        insights: [
            "Meta gives 25 minutes per problem strictly — practice speed. Use a timer during prep.",
            "Interval + merge problems are extremely frequent. Master all interval patterns.",
            "System Design at Meta focuses on social graph infrastructure — news feed, notifications.",
            "Coders at Meta emphasize clean code and testing — mention test cases proactively.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Background + motivation fit call", duration: "20 min" },
            { name: "Technical Screen (2 rounds)", description: "2 coding problems each, 45 min per round", duration: "90 min total" },
            { name: "Onsite (3–4 rounds)", description: "Coding + System Design + Behavioral", duration: "3–4 hours" },
        ],
        requirements: ["Speed under time pressure", "Clean bug-free code", "Social system design knowledge", "Strong array/string fundamentals", "Proactive test case discussion"],
        experiences: [
            { text: "The interviewer was strict about time — I had 2 minutes left when done. Practice speed constantly.", sentiment: "Neutral" },
            { text: "System design asked me to design Instagram Feed — very doable if you've studied news feed design.", sentiment: "Positive" },
            { text: "Got 2 interval problems in coding — both were variations of Merge Intervals.", sentiment: "Positive" },
        ],
        pitfalls: ["Going over time on first problem and rushing second", "Not clarifying constraints before starting", "Missing edge cases (empty arrays, single elements)", "Weak system design on distributed caching"],
        studyPlan: [
            { week: "Week 1", focus: "Intervals, Arrays, Two Pointer", priority: "Critical" },
            { week: "Week 2", focus: "Strings & Sliding Window", priority: "Critical" },
            { week: "Week 3", focus: "Graphs & Union Find", priority: "High" },
            { week: "Week 4", focus: "System Design (News Feed, Messenger)", priority: "High" },
        ],
        processDays: "3–4 weeks",
    },

    microsoft: {
        id: "microsoft",
        name: "Microsoft",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/800px-Microsoft_logo.svg.png",
        category: "Big Tech",
        tier: "FAANG-Adjacent",
        difficulty: "Medium",
        salary: "25–50 LPA",
        rounds: "4–5",
        acceptance: "1.8%",
        rating: "4.3",
        employees: "220k+",
        isHiring: true,
        description: "Microsoft focuses on problem-solving clarity and growth mindset. Medium-level DSA + project deep-dive. More approachable than FAANG.",
        color: "#00A4EF",
        bgGradient: "from-sky-500 to-blue-600",
        topicFrequency: [
            { name: "Trees", value: 25 },
            { name: "Linked List", value: 20 },
            { name: "Arrays", value: 18 },
            { name: "Dynamic Programming", value: 15 },
            { name: "Design", value: 12 },
            { name: "Strings", value: 10 },
        ],
        difficultySplit: { easy: 28, medium: 55, hard: 17 },
        insights: [
            "Microsoft loves Tree problems — master all traversal patterns, LCA, and BST operations.",
            "Growth Mindset is key in behavioral — they want to see how you handle failure and learn.",
            "Resume deep-dives are common — expect technical questions about your projects.",
            "Discuss trade-offs in your design choices; interviewers value reasoning over memorized answers.",
        ],
        interviewProcess: [
            { name: "Recruiter Call", description: "Background + team fit discussion", duration: "20 min" },
            { name: "Online Assessment", description: "2–3 coding problems on HackerRank", duration: "60–90 min" },
            { name: "Technical Phone Screen", description: "1–2 coding + project discussion", duration: "60 min" },
            { name: "Onsite Loop (4–5 rounds)", description: "Coding + Design + As Appropriate (AA) round", duration: "4 hours" },
        ],
        requirements: ["Tree & graph fluency", "Project technical depth", "Growth mindset evidence", "System design for senior roles", "Clear communication of trade-offs"],
        experiences: [
            { text: "All 4 interviewers had great collaborative energy. It felt like problem solving with a colleague, not an interrogation.", sentiment: "Positive" },
            { text: "The AA (As Appropriate) round with the director was unexpected but mostly about leadership and past projects.", sentiment: "Neutral" },
            { text: "Got Tree problems in 3 of 4 coding rounds. Spent 3 weeks just on trees and it paid off.", sentiment: "Positive" },
        ],
        pitfalls: ["Shallow project explanations — they WILL go deep", "Skipping the brute force before optimizing", "Not knowing time complexity of standard library operations", "Neglecting behavioral preparation"],
        studyPlan: [
            { week: "Week 1–2", focus: "Trees (all traversals, BST, LCA)", priority: "Critical" },
            { week: "Week 3", focus: "Linked Lists & Arrays", priority: "Critical" },
            { week: "Week 4", focus: "Dynamic Programming (Medium level)", priority: "High" },
            { week: "Week 5", focus: "System Design + Project Deep Dive Prep", priority: "High" },
        ],
        processDays: "3–6 weeks",
    },

    apple: {
        id: "apple",
        name: "Apple",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/800px-Apple_logo_black.svg.png",
        category: "Big Tech",
        tier: "FAANG",
        difficulty: "Hard",
        salary: "35–70 LPA",
        rounds: "5–7",
        acceptance: "0.3%",
        rating: "4.4",
        employees: "160k+",
        isHiring: false,
        description: "Apple interviews are team-specific and deeply technical. Expect domain-specific questions (iOS, macOS, Distributed Systems) on top of standard DSA.",
        color: "#555555",
        bgGradient: "from-slate-600 to-gray-700",
        topicFrequency: [
            { name: "Binary Search", value: 22 },
            { name: "Dynamic Programming", value: 20 },
            { name: "Linked List", value: 18 },
            { name: "Arrays", value: 15 },
            { name: "Trie", value: 13 },
            { name: "Backtracking", value: 12 },
        ],
        difficultySplit: { easy: 15, medium: 45, hard: 40 },
        insights: [
            "Apple interviews are team-specific — understand the exact team's domain before your loop.",
            "Hard problems are common; being 70% through a Hard problem correctly is often enough to pass.",
            "Privacy and security are cultural values — they may ask how you'd approach user data decisions.",
            "Ask thoughtful questions at the end of each round — Apple values intellectual curiosity.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Background, role fit, compensation expectations", duration: "30 min" },
            { name: "Technical Phone Screen (1–2)", description: "DSA + team-specific technical depth", duration: "60 min each" },
            { name: "Onsite Loop (5–6 rounds)", description: "Coding + System Design + Domain + Values", duration: "5–6 hours" },
        ],
        requirements: ["Domain expertise (iOS/Systems/ML per team)", "Hard problem solving comfort", "Privacy-first thinking", "Intellectual curiosity", "Ownership mindset"],
        experiences: [
            { text: "The interviewers were very specific to the team's tech stack. General DSA prep wasn't enough — know the domain.", sentiment: "Neutral" },
            { text: "6 rounds in one day was exhausting but everyone was professional and respectful.", sentiment: "Positive" },
            { text: "Hard problems in rounds 3 and 5. Got partial credit for solid reasoning even without full solution.", sentiment: "Positive" },
        ],
        pitfalls: ["Preparing generically without team-specific research", "Giving up on Hard problems too early", "Not asking clarifying domain questions", "Poor energy management across 6 rounds"],
        studyPlan: [
            { week: "Week 1–2", focus: "Binary Search + Backtracking", priority: "Critical" },
            { week: "Week 3–4", focus: "DP (Hard level) + Trie", priority: "Critical" },
            { week: "Week 5", focus: "Team-specific domain deep dive", priority: "Critical" },
            { week: "Week 6", focus: "System Design + Distributed Systems", priority: "High" },
        ],
        processDays: "4–8 weeks",
    },

    netflix: {
        id: "netflix",
        name: "Netflix",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/800px-Netflix_2015_logo.svg.png",
        category: "Big Tech",
        tier: "FAANG-Adjacent",
        difficulty: "Hard",
        salary: "80–150 LPA",
        rounds: "4–6",
        acceptance: "0.15%",
        rating: "4.0",
        employees: "13k+",
        isHiring: false,
        description: "Netflix hires very selectively with Freedom & Responsibility culture. Compensation is top-of-market but expectations are extremely high.",
        color: "#E50914",
        bgGradient: "from-red-600 to-rose-700",
        topicFrequency: [
            { name: "Design", value: 30 },
            { name: "Arrays", value: 22 },
            { name: "Dynamic Programming", value: 18 },
            { name: "Linked List", value: 12 },
            { name: "Graphs", value: 10 },
            { name: "Sliding Window", value: 8 },
        ],
        difficultySplit: { easy: 10, medium: 40, hard: 50 },
        insights: [
            "Netflix pays top of market — they expect top of market performance. No mid-level hires.",
            "Freedom & Responsibility culture: they'll probe how you handle autonomy and make decisions.",
            "Streaming systems design is key — know CDN, video transcoding, and adaptive bitrate.",
            "Cultural fit matters as much as technical excellence at Netflix.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Culture fit + background", duration: "30 min" },
            { name: "Hiring Manager Call", description: "Technical depth + team fit discussion", duration: "60 min" },
            { name: "Technical Screens (2–3)", description: "Coding + System Design", duration: "60 min each" },
            { name: "Onsite (Culture Fit)", description: "Values-based interviews with multiple teams", duration: "3–4 hours" },
        ],
        requirements: ["Senior-level system design", "Streaming/CDN knowledge", "Freedom & Responsibility alignment", "Autonomous decision making", "Top-tier coding fluency"],
        experiences: [
            { text: "Was asked to design Netflix's recommendation system end-to-end. Very open-ended — structure your answer well.", sentiment: "Neutral" },
            { text: "Culture fit round was really 'would we trust you with 0 management?' — they want extreme ownership.", sentiment: "Neutral" },
        ],
        pitfalls: ["Not knowing Netflix's technical stack (Chaos Monkey, Zuul, Hystrix)", "Weak culture fit answers around autonomy", "Underselling compensation expectations upfront", "Over-engineering solutions instead of pragmatic choices"],
        studyPlan: [
            { week: "Week 1–2", focus: "Hard DP + Design Problems", priority: "Critical" },
            { week: "Week 3–4", focus: "Streaming Systems Design", priority: "Critical" },
            { week: "Week 5", focus: "Netflix Engineering Blog + Culture Study", priority: "Critical" },
        ],
        processDays: "3–6 weeks",
    },

    uber: {
        id: "uber",
        name: "Uber",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Uber_logo_2018.png/800px-Uber_logo_2018.png",
        category: "Unicorn",
        tier: "Top Startup",
        difficulty: "Medium-Hard",
        salary: "28–55 LPA",
        rounds: "4–5",
        acceptance: "1.0%",
        rating: "3.9",
        employees: "32k+",
        isHiring: true,
        description: "Uber focuses on geo/mapping systems and high-scale distributed design. Expect graph problems, location algorithms, and backend system design.",
        color: "#000000",
        bgGradient: "from-gray-800 to-slate-900",
        topicFrequency: [
            { name: "Graphs", value: 28 },
            { name: "Strings", value: 18 },
            { name: "Design", value: 17 },
            { name: "Math", value: 14 },
            { name: "Backtracking", value: 13 },
            { name: "Intervals", value: 10 },
        ],
        difficultySplit: { easy: 12, medium: 52, hard: 36 },
        insights: [
            "Uber loves graph problems because their core product is literally a graph (maps, routing).",
            "Design questions often involve real-time location tracking and ride matching systems.",
            "Hard Math problems appear more frequently than at other companies — practice geometry/grid.",
            "They move fast — response time from onsite to offer is usually 1–2 weeks.",
        ],
        interviewProcess: [
            { name: "Online Assessment", description: "2 coding problems on HackerRank", duration: "90 min" },
            { name: "Phone Screen", description: "1–2 coding + background check", duration: "60 min" },
            { name: "Onsite (4 rounds)", description: "2 coding + 1 system design + 1 behavioral", duration: "3–4 hours" },
        ],
        requirements: ["Strong graph algorithm knowledge", "Real-time system design", "Analytical thinking", "Geospatial problem intuition", "Move fast mentality"],
        experiences: [
            { text: "Got a geo routing problem that I'd never seen before. Stay calm and build from first principles.", sentiment: "Neutral" },
            { text: "System design was about designing Uber Surge Pricing — very interesting and domain-specific.", sentiment: "Positive" },
        ],
        pitfalls: ["Not knowing basic geo algorithms (Dijkstra, A*)", "Generic system design answers not tailored to Uber's domain", "Slow initial approach — they value moving fast"],
        studyPlan: [
            { week: "Week 1–2", focus: "Graphs (Dijkstra, A*, Topological Sort)", priority: "Critical" },
            { week: "Week 3", focus: "Design (Ride Matching, Surge Pricing)", priority: "Critical" },
            { week: "Week 4", focus: "Hard Math + Backtracking problems", priority: "High" },
        ],
        processDays: "2–4 weeks",
    },

    linkedin: {
        id: "linkedin",
        name: "LinkedIn",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png",
        category: "Big Tech",
        tier: "Top Tech",
        difficulty: "Medium",
        salary: "24–48 LPA",
        rounds: "4–5",
        acceptance: "1.5%",
        rating: "4.2",
        employees: "20k+",
        isHiring: true,
        description: "LinkedIn interviews are well-structured and friendly. Graph and social network algorithms are core themes given their product domain.",
        color: "#0A66C2",
        bgGradient: "from-blue-600 to-blue-800",
        topicFrequency: [
            { name: "Graphs", value: 26 },
            { name: "Dynamic Programming", value: 20 },
            { name: "Design", value: 18 },
            { name: "Strings", value: 16 },
            { name: "Trees", value: 12 },
            { name: "Backtracking", value: 8 },
        ],
        difficultySplit: { easy: 20, medium: 60, hard: 20 },
        insights: [
            "LinkedIn's graph-heavy product means you'll likely face social network traversal problems.",
            "Design questions often involve feed ranking, connection suggestions, or notification systems.",
            "They weigh collaboration and communication heavily — mention how you work with PMs and designers.",
            "LinkedIn Reach (their internal coding platform) may be used — practice reading solutions aloud.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Background + role expectations", duration: "30 min" },
            { name: "Technical Phone Screen", description: "1–2 coding problems", duration: "60 min" },
            { name: "Onsite (4 rounds)", description: "2 coding + 1 system design + 1 culture", duration: "3–4 hours" },
        ],
        requirements: ["Graph algorithm fluency", "Social systems design", "Strong communication", "Data-driven mindset", "Collaborative approach"],
        experiences: [
            { text: "One of the friendliest interview experiences I've had. Interviewer genuinely wanted me to succeed.", sentiment: "Positive" },
            { text: "Graph problem was surprisingly hard for a Medium rating. Practice BFS/DFS until it's reflexive.", sentiment: "Neutral" },
        ],
        pitfalls: ["Not connecting solutions to LinkedIn's actual product use cases", "Ignoring medium DP problems", "Not mentioning collaboration in behavioral rounds"],
        studyPlan: [
            { week: "Week 1–2", focus: "Graphs + BFS/DFS + Union Find", priority: "Critical" },
            { week: "Week 3", focus: "DP (Medium) + Strings", priority: "High" },
            { week: "Week 4", focus: "Social Feed System Design", priority: "High" },
        ],
        processDays: "2–4 weeks",
    },

    adobe: {
        id: "adobe",
        name: "Adobe",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Adobe_Corporate_Logo.png/800px-Adobe_Corporate_Logo.png",
        category: "Enterprise Tech",
        tier: "Top Tech",
        difficulty: "Medium",
        salary: "20–40 LPA",
        rounds: "3–5",
        acceptance: "2.5%",
        rating: "4.1",
        employees: "30k+",
        isHiring: true,
        description: "Adobe focuses on creative problem solving. Image processing, matrix manipulation, and dynamic programming are common themes reflecting their product suite.",
        color: "#FF0000",
        bgGradient: "from-red-500 to-rose-600",
        topicFrequency: [
            { name: "Dynamic Programming", value: 24 },
            { name: "Arrays/Matrix", value: 22 },
            { name: "Intervals", value: 16 },
            { name: "Graphs", value: 14 },
            { name: "Stack", value: 12 },
            { name: "Sliding Window", value: 12 },
        ],
        difficultySplit: { easy: 15, medium: 58, hard: 27 },
        insights: [
            "Adobe's creative tools background means image/matrix problems appear frequently.",
            "The interview atmosphere is collaborative — they expect you to think out loud from the start.",
            "System design at Adobe often involves document editing, versioning, or creative asset pipelines.",
            "Adobe values product sense — understand how DSA connects to their Creative Cloud products.",
        ],
        interviewProcess: [
            { name: "Online Assessment", description: "2–3 coding problems on HackerRank", duration: "90 min" },
            { name: "Phone Screen", description: "1 coding + CS fundamentals", duration: "60 min" },
            { name: "Onsite (3–4 rounds)", description: "Coding + LLD + System Design + HR", duration: "3–4 hours" },
        ],
        requirements: ["Matrix/2D array fluency", "DP problem patterns", "LLD (design document editor)", "Communication skills", "Product curiosity"],
        experiences: [
            { text: "Was asked to implement a simplified version of Photoshop's lasso selection tool. Be ready for product-adjacent problems.", sentiment: "Neutral" },
            { text: "Very collaborative atmosphere. Interviewer helped when stuck without penalizing.", sentiment: "Positive" },
        ],
        pitfalls: ["Ignoring LLD rounds", "Not connecting solutions to creative/image processing context", "Weak DP foundations at Hard level"],
        studyPlan: [
            { week: "Week 1", focus: "Matrix Problems + 2D Arrays", priority: "Critical" },
            { week: "Week 2–3", focus: "Dynamic Programming (1D & 2D)", priority: "Critical" },
            { week: "Week 4", focus: "LLD (Document Editor, Creative Tools)", priority: "High" },
        ],
        processDays: "2–4 weeks",
    },

    salesforce: {
        id: "salesforce",
        name: "Salesforce",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Salesforce.com_logo.svg/800px-Salesforce.com_logo.svg.png",
        category: "Enterprise Tech",
        tier: "Top Tech",
        difficulty: "Easy-Medium",
        salary: "22–45 LPA",
        rounds: "3–4",
        acceptance: "3.5%",
        rating: "4.0",
        employees: "80k+",
        isHiring: true,
        description: "Salesforce has a more approachable interview process. Strong emphasis on CRM domain knowledge and scalable cloud system design alongside standard DSA.",
        color: "#00A1E0",
        bgGradient: "from-cyan-500 to-blue-600",
        topicFrequency: [
            { name: "Stack", value: 25 },
            { name: "Arrays", value: 22 },
            { name: "Graphs", value: 18 },
            { name: "Trees", value: 15 },
            { name: "Dynamic Programming", value: 12 },
            { name: "Design", value: 8 },
        ],
        difficultySplit: { easy: 30, medium: 55, hard: 15 },
        insights: [
            "Salesforce interviews are more accessible than FAANG — Medium problems are usually sufficient.",
            "CRM system design knowledge is a big plus — understand multi-tenancy and SaaS architecture.",
            "Trailhead (Salesforce's learning platform) culture means they value continuous learners.",
            "Behavioral focus is significant — they value Ohana (family) culture alignment.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Background + Ohana culture fit", duration: "30 min" },
            { name: "Online Assessment", description: "2 coding problems", duration: "60 min" },
            { name: "Onsite (3 rounds)", description: "1–2 coding + 1 system design + HR", duration: "2–3 hours" },
        ],
        requirements: ["Stack/Queue fundamentals", "Multi-tenant system design", "Ohana culture values", "Agile/Scrum understanding", "API design basics"],
        experiences: [
            { text: "Most welcoming interview process I've experienced. The Ohana culture is genuine — interviewers genuinely cared.", sentiment: "Positive" },
            { text: "System design was about a multi-tenant CRM platform. Know SaaS architecture basics.", sentiment: "Neutral" },
        ],
        pitfalls: ["Underestimating system design round (SaaS-specific patterns matter)", "Weak behavioral answers around teamwork", "Rushing past Easy problems without clean code"],
        studyPlan: [
            { week: "Week 1", focus: "Stack, Queue, Arrays", priority: "Critical" },
            { week: "Week 2", focus: "Graphs + Trees (Medium level)", priority: "High" },
            { week: "Week 3", focus: "SaaS/CRM System Design", priority: "High" },
            { week: "Week 4", focus: "Behavioral + Ohana culture prep", priority: "Medium" },
        ],
        processDays: "2–3 weeks",
    },

    nvidia: {
        id: "nvidia",
        name: "NVIDIA",
        logo: "https://upload.wikimedia.org/wikipedia/sco/thumb/2/21/Nvidia_logo.svg/800px-Nvidia_logo.svg.png",
        category: "Hardware/AI",
        tier: "Top Tech",
        difficulty: "Hard",
        salary: "40–80 LPA",
        rounds: "4–6",
        acceptance: "0.8%",
        rating: "4.3",
        employees: "30k+",
        isHiring: true,
        description: "NVIDIA blends hardware and software deeply. Expect GPU architecture questions, parallel computing, CUDA, and algorithmic problems with performance constraints.",
        color: "#76B900",
        bgGradient: "from-green-500 to-emerald-700",
        topicFrequency: [
            { name: "Arrays/Matrix", value: 28 },
            { name: "Backtracking", value: 20 },
            { name: "Graphs", value: 18 },
            { name: "Bit Manipulation", value: 14 },
            { name: "Math", value: 12 },
            { name: "Design", value: 8 },
        ],
        difficultySplit: { easy: 10, medium: 42, hard: 48 },
        insights: [
            "NVIDIA expects GPU/parallel computing knowledge — know CUDA basics for hardware-adjacent roles.",
            "Matrix/grid problems reflect their GPU architecture domain — heavily practice 2D traversals.",
            "Hard algorithmic problems dominate — especially Backtracking with constraints.",
            "For ML infrastructure roles, know PyTorch, CUDA kernels, and tensor operations.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Background + team fit", duration: "30 min" },
            { name: "Technical Phone Screen (2)", description: "Domain-specific + DSA coding", duration: "60 min each" },
            { name: "Onsite (4–5 rounds)", description: "Coding + Architecture + Domain + Behavioral", duration: "4–5 hours" },
        ],
        requirements: ["GPU architecture knowledge", "Parallel computing fundamentals", "Hard DSA proficiency", "Matrix/grid algorithm fluency", "C++ proficiency preferred"],
        experiences: [
            { text: "Was asked about CUDA thread blocks in a system design question for the GPU programming role — very domain specific.", sentiment: "Neutral" },
            { text: "DSA rounds were genuinely Hard level — harder than typical FAANG. Prepare well.", sentiment: "Negative" },
            { text: "The team is brilliant and interviews feel like intellectual conversations once you get past the hard problems.", sentiment: "Positive" },
        ],
        pitfalls: ["Insufficient GPU/parallel computing domain knowledge for hardware roles", "Weak Backtracking and DP at Hard level", "Not knowing C++ for systems/driver roles"],
        studyPlan: [
            { week: "Week 1–2", focus: "Hard Backtracking + Matrix Problems", priority: "Critical" },
            { week: "Week 3", focus: "Bit Manipulation + Math Problems", priority: "Critical" },
            { week: "Week 4–5", focus: "GPU Architecture + CUDA Basics", priority: "Critical" },
        ],
        processDays: "4–8 weeks",
    },

    bytedance: {
        id: "bytedance",
        name: "ByteDance",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/ByteDance_Official_Logo_RGB.svg/800px-ByteDance_Official_Logo_RGB.svg.png",
        category: "Big Tech",
        tier: "Top Tech",
        difficulty: "Hard",
        salary: "30–65 LPA",
        rounds: "4–5",
        acceptance: "0.8%",
        rating: "3.8",
        employees: "150k+",
        isHiring: true,
        description: "ByteDance (TikTok's parent) moves extremely fast. Interviews are rigorous with a preference for greedy and DP heavy problems. Fast-paced culture.",
        color: "#010101",
        bgGradient: "from-slate-800 to-zinc-900",
        topicFrequency: [
            { name: "Greedy", value: 26 },
            { name: "Dynamic Programming", value: 24 },
            { name: "Sliding Window", value: 18 },
            { name: "Graphs", value: 14 },
            { name: "Queue/Deque", value: 10 },
            { name: "Math", value: 8 },
        ],
        difficultySplit: { easy: 8, medium: 45, hard: 47 },
        insights: [
            "ByteDance heavily favors Greedy + DP problems — build deep intuition for both.",
            "The interview pace is very fast — they want optimal solutions quickly.",
            "Recommendation algorithm knowledge (for TikTok roles) is a differentiator.",
            "Chinese tech work culture applies — be prepared for fast iterations and high output expectations.",
        ],
        interviewProcess: [
            { name: "OA Screen", description: "2–3 Hard problems, timed", duration: "120 min" },
            { name: "Technical Phone Screens (2)", description: "Coding with optimization focus", duration: "60 min each" },
            { name: "Onsite (3–4 rounds)", description: "Coding + System Design + Behavioral", duration: "3–4 hours" },
        ],
        requirements: ["Greedy algorithm mastery", "Hard DP patterns", "Speed under pressure", "Recommendation systems knowledge (for TikTok roles)", "Global/cross-cultural collaboration"],
        experiences: [
            { text: "OA had 3 Hard problems in 2 hours. You must be fast AND accurate. No partial credit feeling.", sentiment: "Negative" },
            { text: "System design for TikTok feed was super interesting — deep dive into ML recommendation systems.", sentiment: "Positive" },
        ],
        pitfalls: ["Slow problem solving approach — speed is explicitly valued", "Weak Greedy intuition for interval/scheduling problems", "Not researching TikTok's recommendation algorithm basics"],
        studyPlan: [
            { week: "Week 1–2", focus: "Greedy (all patterns) + Sliding Window", priority: "Critical" },
            { week: "Week 3–4", focus: "Hard DP (Interval, String, 2D)", priority: "Critical" },
            { week: "Week 5", focus: "Recommendation Systems + TikTok design", priority: "High" },
        ],
        processDays: "2–4 weeks",
    },

    atlassian: {
        id: "atlassian",
        name: "Atlassian",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Atlassian-logo.svg/800px-Atlassian-logo.svg.png",
        category: "Enterprise Tech",
        tier: "Top Tech",
        difficulty: "Medium",
        salary: "22–45 LPA",
        rounds: "3–4",
        acceptance: "3.0%",
        rating: "4.2",
        employees: "11k+",
        isHiring: true,
        description: "Atlassian (Jira, Confluence) has a values-driven, remote-first interview. Good mix of DSA and collaborative design. Strong emphasis on Open Company values.",
        color: "#0052CC",
        bgGradient: "from-blue-700 to-indigo-800",
        topicFrequency: [
            { name: "Stack", value: 24 },
            { name: "Dynamic Programming", value: 20 },
            { name: "Trees", value: 18 },
            { name: "Arrays", value: 16 },
            { name: "Strings", value: 14 },
            { name: "Graphs", value: 8 },
        ],
        difficultySplit: { easy: 22, medium: 60, hard: 18 },
        insights: [
            "Atlassian's values (Open, Honest, Collaborative) are probed throughout — prepare specific examples.",
            "They use a 'Values Interview' as a separate round — it's as important as technical.",
            "Remote-first since 2020 — communication quality matters significantly in virtual interviews.",
            "Collaborative design problems where you co-solve with the interviewer are common.",
        ],
        interviewProcess: [
            { name: "Recruiter Screen", description: "Background + values alignment", duration: "30 min" },
            { name: "Technical Screen", description: "1–2 coding problems", duration: "60 min" },
            { name: "Values Interview", description: "Dedicated behavioral round on Atlassian values", duration: "60 min" },
            { name: "Technical Onsite (2 rounds)", description: "Coding + System Design", duration: "2 hours" },
        ],
        requirements: ["Stack/DP fundamentals", "Open & collaborative communication", "Remote-work self-discipline", "Jira/Confluence domain awareness", "Values alignment"],
        experiences: [
            { text: "The Values Interview was the most unique round I've had. Prepare detailed stories for each of their 5 values.", sentiment: "Neutral" },
            { text: "Very collaborative coding round — we designed together rather than me presenting a solution.", sentiment: "Positive" },
        ],
        pitfalls: ["Treating values interview as less important than technical", "Poor asynchronous communication signals in a remote setting", "Not researching Atlassian's product suite (Jira, Confluence, Trello, Bitbucket)"],
        studyPlan: [
            { week: "Week 1", focus: "Stack, DP, Trees (Medium level)", priority: "Critical" },
            { week: "Week 2", focus: "Atlassian Values + STAR stories", priority: "Critical" },
            { week: "Week 3", focus: "System Design (Issue Tracking, Wiki)", priority: "High" },
        ],
        processDays: "2–4 weeks",
    },

    airbnb: {
        id: "airbnb",
        name: "Airbnb",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_B%C3%A9lo.svg/800px-Airbnb_Logo_B%C3%A9lo.svg.png",
        category: "Unicorn",
        tier: "Top Startup",
        difficulty: "Hard",
        salary: "30–60 LPA",
        rounds: "4–5",
        acceptance: "0.9%",
        rating: "4.0",
        employees: "7k+",
        isHiring: false,
        description: "Airbnb's interviews have a creative, product-first angle. Expect Hard-level algorithmic problems paired with product design and hospitality industry insights.",
        color: "#FF5A5F",
        bgGradient: "from-rose-500 to-pink-600",
        topicFrequency: [
            { name: "Trie", value: 22 },
            { name: "Dynamic Programming", value: 20 },
            { name: "Design", value: 18 },
            { name: "Greedy", value: 16 },
            { name: "Graphs", value: 14 },
            { name: "Backtracking", value: 10 },
        ],
        difficultySplit: { easy: 8, medium: 42, hard: 50 },
        insights: [
            "Airbnb's product obsession means design problems often involve booking, availability, or search systems.",
            "Hard Trie problems are uniquely common at Airbnb — master Trie thoroughly.",
            "Cultural fit matters hugely — they want people passionate about travel and hospitality.",
            "Expect creative algorithmic problems that aren't directly on LeetCode — practice first-principles thinking.",
        ],
        interviewProcess: [
            { name: "Phone Screen", description: "1 coding problem + motivation", duration: "60 min" },
            { name: "Technical Screens (2)", description: "DSA problems + brief design", duration: "60 min each" },
            { name: "Onsite (3–4 rounds)", description: "Coding + System Design + Cross-functional + Culture", duration: "3–4 hours" },
        ],
        requirements: ["Hard DSA (especially Trie)", "Booking/search system design", "Product passion", "Hospitality domain empathy", "Creative problem solving"],
        experiences: [
            { text: "Was given a custom Trie problem I'd never seen. Knowing the pattern deeply helped me solve it from scratch.", sentiment: "Positive" },
            { text: "System design was designing Airbnb's search + availability system — super relevant and interesting.", sentiment: "Positive" },
            { text: "Culture round is real — they want to see genuine passion for travel, not lip service.", sentiment: "Neutral" },
        ],
        pitfalls: ["Treating Trie as a minor topic — it's a core Airbnb topic", "Generic system design answers not tailored to marketplace/booking domains", "Lacking genuine enthusiasm for Airbnb's mission"],
        studyPlan: [
            { week: "Week 1–2", focus: "Trie + Hard DP", priority: "Critical" },
            { week: "Week 3", focus: "Booking/Marketplace System Design", priority: "Critical" },
            { week: "Week 4", focus: "Backtracking + Greedy", priority: "High" },
        ],
        processDays: "3–5 weeks",
    },
};

// ─── Helper: derive difficulty split and topic frequency from questions ──────
function enrichCompanyData(companyId) {
    const meta = COMPANY_META[companyId];
    const questions = RAW_QUESTIONS[companyId] || [];

    // Auto-derive counts if not provided
    const total = questions.length;
    const easy = questions.filter(q => q.difficulty === "Easy").length;
    const medium = questions.filter(q => q.difficulty === "Medium").length;
    const hard = questions.filter(q => q.difficulty === "Hard").length;

    return {
        ...meta,
        questions,
        questionCount: total,
        // Override difficulty split with real counts if needed
        difficultySplit: meta.difficultySplit || {
            easy: Math.round((easy / total) * 100),
            medium: Math.round((medium / total) * 100),
            hard: Math.round((hard / total) * 100),
        },
    };
}

// ─── Public API ──────────────────────────────────────────────────────────────

export const COMPANIES = Object.keys(COMPANY_META).map(id => enrichCompanyData(id));

export function getCompanyById(id) {
    return COMPANIES.find(c => c.id === id);
}

export const CATEGORIES = ["All", ...new Set(COMPANIES.map(c => c.category))];
export const TIERS = ["All", ...new Set(COMPANIES.map(c => c.tier))];
export const DIFFICULTIES = ["All", "Easy", "Easy-Medium", "Medium", "Medium-Hard", "Hard"];